"""initial schema

Revision ID: 895e1dd1b541
Revises: 
Create Date: 2026-06-25 16:54:12.758287

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '895e1dd1b541'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('courses', 'course_name',
               existing_type=mysql.VARCHAR(length=150),
               nullable=True)
    op.drop_index(op.f('course_code'), table_name='courses')
    op.alter_column('departments', 'dept_name',
               existing_type=mysql.VARCHAR(length=100),
               nullable=True)
    op.alter_column('enrollments', 'grade',
               existing_type=mysql.CHAR(length=2),
               type_=sa.String(length=2),
               existing_nullable=True)
    op.add_column('professors', sa.Column('first_name', sa.String(length=100), nullable=True))
    op.drop_index(op.f('email'), table_name='professors')
    op.drop_column('professors', 'prof_name')
    op.alter_column('students', 'first_name',
               existing_type=mysql.VARCHAR(length=50),
               nullable=True)
    op.alter_column('students', 'last_name',
               existing_type=mysql.VARCHAR(length=50),
               nullable=True)
    op.alter_column('students', 'email',
               existing_type=mysql.VARCHAR(length=100),
               nullable=True)
    op.drop_index(op.f('email'), table_name='students')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('email'), 'students', ['email'], unique=True)
    op.alter_column('students', 'email',
               existing_type=mysql.VARCHAR(length=100),
               nullable=False)
    op.alter_column('students', 'last_name',
               existing_type=mysql.VARCHAR(length=50),
               nullable=False)
    op.alter_column('students', 'first_name',
               existing_type=mysql.VARCHAR(length=50),
               nullable=False)
    op.add_column('professors', sa.Column('prof_name', mysql.VARCHAR(length=100), nullable=False))
    op.create_index(op.f('email'), 'professors', ['email'], unique=True)
    op.drop_column('professors', 'first_name')
    op.alter_column('enrollments', 'grade',
               existing_type=sa.String(length=2),
               type_=mysql.CHAR(length=2),
               existing_nullable=True)
    op.alter_column('departments', 'dept_name',
               existing_type=mysql.VARCHAR(length=100),
               nullable=False)
    op.create_index(op.f('course_code'), 'courses', ['course_code'], unique=True)
    op.alter_column('courses', 'course_name',
               existing_type=mysql.VARCHAR(length=150),
               nullable=False)
    # ### end Alembic commands ###
